[manager]
sort_by         = "alphabetical"
sort_dir_first  = true
sort_sensitive  = false
sort_reverse    = false
sort_translit   = true

[shell]
shell = "zsh"

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5
